fix(ci): handle concurrent hotfix and release (#1191)
* fix(ci): handle concurrent hotfix and release

* fixed missing inputs in nightly and libzmq workflow

* Update action.yml

---------

Co-authored-by: May <110405507+paul-oureib@users.noreply.github.com>

diff --git a/.github/actions/delivery/action.yml b/.github/actions/delivery/action.yml
--- a/.github/actions/delivery/action.yml
+++ b/.github/actions/delivery/action.yml
@@ -19,6 +19,12 @@ inputs:
   stability:
     description: "The package stability (stable, testing, unstable)"
     required: true
+  release_type:
+    description: "Type of release (hotfix, release)"
+    required: true
+  release_cloud:
+    description: "Release context (cloud or not cloud)"
+    required: true
 
 runs:
   using: "composite"
@@ -49,6 +55,8 @@ runs:
     - if: ${{ env.extfile == 'rpm' }}
       name: Publish RPMs
       run: |
+        set -eux
+
         FILES="*.${{ env.extfile }}"
 
         echo "[DEBUG] - Version: ${{ inputs.version }}"
@@ -64,8 +72,17 @@ runs:
           exit 1
         fi
 
+        # DEBUG
+        echo "[DEBUG] - Version: ${{ inputs.version }}"
+        echo "[DEBUG] - Distrib: ${{ inputs.distrib }}"
+        echo "[DEBUG] - module_name: ${{ inputs.module_name }}"
+        echo "[DEBUG] - release_cloud: ${{ inputs.release_cloud }}"
+        echo "[DEBUG] - release_type: ${{ inputs.release_type }}"
+
+        # Create ARCH dirs
         mkdir noarch x86_64
 
+        # Get ARCH target for files to deliver and regroupe them by ARCH
         for FILE in $FILES; do
           echo "[DEBUG] - File: $FILE"
 
@@ -76,13 +93,27 @@ runs:
           mv "$FILE" "$ARCH"
         done
 
+        # Build upload target path based on release_cloud and release_type values
+        # if cloud, deliver to testing-<release_type>
+        # if non-cloud, delivery to testing as usual
+        if [[ ${{ inputs.release_cloud }} -eq 1 && ${{ inputs.release_type }} == "hotfix" ]] || [[ ${{ inputs.release_cloud }} -eq 1 && ${{ inputs.release_type }} == "release" ]]; then
+          ROOT_REPO_PATH="rpm-standard-internal"
+          UPLOAD_REPO_PATH="${{ inputs.version }}/${{ inputs.distrib }}/${{ inputs.stability }}-${{ inputs.release_type }}/$ARCH/RPMS/${{ inputs.module_name }}/"
+        elif [[ ${{ inputs.release_cloud }} -eq 0 ]]; then
+          ROOT_REPO_PATH="rpm-standard"
+          UPLOAD_REPO_PATH="${{ inputs.version }}/${{ inputs.distrib }}/${{ inputs.stability }}/$ARCH/RPMS/${{ inputs.module_name }}/"
+        else
+          echo "Invalid combination of release_type and release_cloud"
+        fi
+
+        # Deliver based on inputs
         for ROOT_REPO_PATH in "rpm-standard" "rpm-standard-internal"; do
           for ARCH in "noarch" "x86_64"; do
             if [ "$(ls -A $ARCH)" ]; then
               if [ "${{ inputs.stability }}" == "stable" ]; then
-                jf rt upload "$ARCH/*.rpm" "$ROOT_REPO_PATH/${{ inputs.version }}/${{ inputs.distrib }}/${{ inputs.stability }}/$ARCH/RPMS/${{ inputs.module_name }}/" --flat
+                echo "[DEBUG] - Stability is ${{ inputs.stability }}, not delivering."
               else
-                jf rt upload "$ARCH/*.rpm" "$ROOT_REPO_PATH/${{ inputs.version }}/${{ inputs.distrib }}/${{ inputs.stability }}/$ARCH/${{ inputs.module_name }}/" --sync-deletes="$ROOT_REPO_PATH/${{ inputs.version }}/${{ inputs.distrib }}/${{ inputs.stability }}/$ARCH/${{ inputs.module_name }}/" --flat
+                jf rt upload "$ARCH/*.rpm" "$ROOT_REPO_PATH/$UPLOAD_REPO_PATH" --flat
               fi
             fi
           done
