enh(ci): fix and enhance deb delivery with custom sync-deletes

diff --git a/.github/actions/delivery/action.yml b/.github/actions/delivery/action.yml
--- a/.github/actions/delivery/action.yml
+++ b/.github/actions/delivery/action.yml
@@ -168,12 +168,43 @@ runs:
           exit 1
         fi
 
-        for FILE in $FILES; do
-          echo "[DEBUG] - File: $FILE"
+        # Cleanup (equivalent to --sync-deletes done with RPMs)
+        # This is a workaround the fact that jfrog cli does not allow upload
+        # of multiple artifacts at once to an APT repository
+
+        # Get list of remote artifacts
+        ARTIFACTS_REMOTE_LIST=$(jf rt search "$ROOT_REPO_PATH/pool/${{ inputs.module_name }}/*_24.10*.deb" --recursive --sort-by=path |jq -r .[].path)
+
+        # Get list of local artifacts
+        ARTIFACTS_LOCAL_LIST=$(dir -1 |grep -E '.*${{ inputs.major_version }}.*.deb')
+
+        # Build list of diff between local and remote artifacts
+        for local_artifact in "${ARTIFACTS_LOCAL_LIST[@]}"; do
+          found=false
+          # Iterate over elements of ARTIFACTS_REMOTE_LIST
+          for remote_artifact in "${ARTIFACTS_REMOTE_LIST[@]}"; do
+            # Compare elements
+            if [ "$local_artifact" == "$remote_artifact" ]; then
+              found=true
+              break
+            fi
+          done
+          # If element not found in ARTIFACTS_REMOTE_LIST, add it to ARTIFACTS_DIFF_LIST
+          if ! $found; then
+            ARTIFACTS_DIFF_LIST+=("$local_artifact")
+          fi
+        done
+
+        # Delete all remote artifacts
+        jf rt delete "$ROOT_REPO_PATH/pool/${{ inputs.module_name }}/*.deb"
+
+        # Upload local artifacts
+        for ARTIFACT in ${ARTIFACTS_LOCAL_LIST[@]}; do
+          echo "[DEBUG] - File: $ARTIFACT"
 
           VERSION=${{ inputs.major_version }}
-          DISTRIB=$(echo $FILE | cut -d '_' -f2 | cut -d '-' -f2)
-          ARCH=$(echo $FILE | cut -d '_' -f3 | cut -d '.' -f1)
+          DISTRIB=$(echo $ARTIFACT | cut -d '_' -f2 | cut -d '-' -f2)
+          ARCH=$(echo $ARTIFACT | cut -d '_' -f3 | cut -d '.' -f1)
 
           echo "[DEBUG] - Major version: $VERSION"
 
@@ -185,11 +216,7 @@ runs:
             ROOT_REPO_PATH="apt-standard-${{ inputs.major_version }}-${{ inputs.stability }}"
           fi
 
-          if [[ "${{ inputs.stability }}" == "stable" ]]; then
-            echo "[DEBUG] - Stability is ${{ inputs.stability }}, not delivering."
-          else
-            jf rt upload "$FILE" "$ROOT_REPO_PATH/pool/${{ inputs.module_name }}/" --deb "${{ inputs.distrib }}/main/$ARCH" --sync-deletes="$ROOT_REPO_PATH/pool/${{ inputs.module_name }}/" --flat
-          fi
+          jf rt upload "$ARTIFACT" "$ROOT_REPO_PATH/pool/${{ inputs.module_name }}/" --deb "${{ inputs.distrib }}/main/$ARCH"
         done
 
         # In case of CMA, we also copy it in /installers
