report changes onto actions/delivery action

diff --git a/.github/actions/delivery/action.yml b/.github/actions/delivery/action.yml
--- a/.github/actions/delivery/action.yml
+++ b/.github/actions/delivery/action.yml
@@ -25,6 +25,9 @@ inputs:
   is_cloud:
     description: "Release context (cloud or not cloud)"
     required: true
+  delivery_type:
+    description: "Delivery to feature or standard repository"
+    required: true
 
 runs:
   using: "composite"
@@ -53,6 +56,57 @@ runs:
         JF_URL: https://centreon.jfrog.io
         JF_ACCESS_TOKEN: ${{ inputs.artifactory_token }}
 
+    - if: inputs.delivery_type == 'feature' && env.extfile = 'rpm'
+      name: Create a rpm feature repository
+      shell: bash
+      env:
+        JF_URL: https://centreon.jfrog.io
+        JF_ACCESS_TOKEN: ${{ inputs.artifactory_token }}
+      run: |
+        set -eu
+        . .version
+        major_version=$(grep -E "MAJOR" .version | cut -d '=' -f2)
+        feature_ticket=$(echo "${{ github.event.pull_request.head.ref }}" | grep -oE 'MON-[0-9]+')
+        echo "[INFO] Creating a rpm feature repository if it does not exist"
+
+        curl -X POST \
+            -H "Authorization: Bearer ${{ secrets.CENTREON_TECHNIQUE_PAT }}" \
+            -H "Accept: application/vnd.github.v3+json" \
+            https://api.github.com/repos/centreon/delivery-tooling/dispatches \
+            -d "$(jq -n \
+              --arg major_version "$major_version" \
+              --arg repo_type "feature" \
+              --arg feature_ticket "$feature_ticket" \
+              '{
+                event_type: "create-feature-repositories",
+                client_payload: {
+                  major_version: $major_version,
+                  repo_type: $repo_type,
+                  feature_ticket: $feature_ticket
+                }
+              }'
+            )"
+
+        response=""
+        attempt=0
+        until [[ $(echo "$response" | tr -d '\n' | tail -c 3) -eq 200 || $attempt -ge 40 ]]; do
+          attempt=$(( attempt+1 ))
+          echo "[INFO] Checking if the feature repository has been created... [ATTEMPT $attempt]"
+          response=$(curl \
+            --write-out "%{http_code}" \
+            --request GET \
+            --url "${{ env.JF_URL }}/artifactory/api/v2/repositories/rpm-standard-feature-$feature_ticket" \
+            --header "Authorization: Bearer ${{ env.JF_ACCESS_TOKEN }}" \
+            --header "Content-Type: application/json"
+          )
+          sleep 15
+        done
+
+        if [[ $attempt -ge 40 ]]; then
+          echo "::error::Timeout waiting for repository creation. Aborting delivery process. Please contact someone from the DevSecOps team."
+          exit 1
+        fi
+
     - if: ${{ env.extfile == 'rpm' }}
       name: Publish RPMs
       run: |
@@ -67,6 +121,7 @@ runs:
         echo "[DEBUG] - is_cloud: ${{ inputs.is_cloud }}"
         echo "[DEBUG] - release_type: ${{ inputs.release_type }}"
         echo "[DEBUG] - stability: ${{ inputs.stability }}"
+        echo "[DEBUG] - delivery_type: ${{ inputs.delivery_type }}"
 
         # Make sure all required inputs are NOT empty
         if [[ -z "${{ inputs.module_name }}" || -z "${{ inputs.distrib }}" || -z ${{ inputs.stability }} || -z ${{ inputs.major_version }} || -z "${{ inputs.is_cloud }}" ]]; then
@@ -92,26 +147,33 @@ runs:
         # if cloud + hotfix or cloud + release, deliver to internal testing-<release_type>
         # if cloud + develop, delivery to internal unstable
         # if non-cloud, delivery to onprem testing or unstable
+        # if feature delivery, delivery to dedicated feature repository
+
+        # FEATURE REPOSITORY
+        if [[ "${{ inputs.delivery_type }}" == "feature" ]]; then
+          echo "[DEBUG] : Delivery to feature repositories, using rpm-feature repo."
+          ROOT_REPO_PATHS="rpm-standard-$(echo "${{ github.head_ref || github.ref_name }}" | grep -oP '^.*-MON-[0-9]+')"
+          UPLOAD_REPO_PATH="${{ inputs.version }}/${{ inputs.distrib }}/${{ inputs.stability }}/$ARCH/${{ inputs.module_name }}/"
 
         # CLOUD + HOTFIX + REPO STANDARD INTERNAL OR CLOUD + RELEASE + REPO STANDARD INTERNAL
-        if [[ "${{ inputs.is_cloud }}" == "true" && ( "${{ inputs.release_type }}" == "hotfix" || "${{ inputs.release_type }}" == "release" ) ]]; then
+        elif [[ "${{ inputs.delivery_type }}" == "classic" ]] && [[ "${{ inputs.is_cloud }}" == "true" && ( "${{ inputs.release_type }}" == "hotfix" || "${{ inputs.release_type }}" == "release" ) ]]; then
           echo "[DEBUG] : Release cloud + ${{ inputs.release_type }}, using rpm-standard-internal."
           ROOT_REPO_PATHS="rpm-standard-internal"
           UPLOAD_REPO_PATH="${{ inputs.major_version }}/${{ inputs.distrib }}/${{ inputs.stability }}-${{ inputs.release_type }}/$ARCH/${{ inputs.module_name }}/"
 
         # CLOUD + NOT HOTFIX OR CLOUD + NOT RELEASE + REPO STANDARD INTERNAL
-        elif [[ "${{ inputs.is_cloud }}" == "true" && ( "${{ inputs.release_type }}" != "hotfix" && "${{ inputs.release_type }}" != "release" ) ]]; then
+        elif [[ "${{ inputs.delivery_type }}" == "classic" ]] && [[ "${{ inputs.is_cloud }}" == "true" && ( "${{ inputs.release_type }}" != "hotfix" && "${{ inputs.release_type }}" != "release" ) ]]; then
           echo "[DEBUG] : Release cloud + NOT ${{ inputs.release_type }}, using rpm-standard-internal."
           ROOT_REPO_PATHS="rpm-standard-internal"
           UPLOAD_REPO_PATH="${{ inputs.major_version }}/${{ inputs.distrib }}/${{ inputs.stability }}-${{ inputs.release_type }}/$ARCH/${{ inputs.module_name }}/"
 
         # NON-CLOUD + (HOTFIX OR RELEASE) + REPO STANDARD
-        elif [[ "${{ inputs.is_cloud }}" == "false" ]]; then
+        elif [[ "${{ inputs.delivery_type }}" == "classic" ]] && [[ "${{ inputs.is_cloud }}" == "false" ]]; then
           echo "[DEBUG] : NOT Release cloud + ${{ inputs.release_type }}, using rpm-standard."
           ROOT_REPO_PATHS="rpm-standard"
           UPLOAD_REPO_PATH="${{ inputs.major_version }}/${{ inputs.distrib }}/${{ inputs.stability }}/$ARCH/${{ inputs.module_name }}/"
 
-        #  NOT VALID, DO NOT DELIVER
+        # NOT VALID, DO NOT DELIVER
         else
           echo "::error:: Invalid combination of release_type [${{ inputs.release_type }}] and is_cloud [${{ inputs.is_cloud }}]"
           exit 1
@@ -129,11 +191,16 @@ runs:
                 jf rt upload "$ARCH/*.rpm" "$ROOT_REPO_PATH/${{ inputs.major_version }}/${{ inputs.distrib }}/${{ inputs.stability }}/$ARCH/${{ inputs.module_name }}/" --sync-deletes="$ROOT_REPO_PATH/${{ inputs.major_version }}/${{ inputs.distrib }}/${{ inputs.stability }}/$ARCH/${{ inputs.module_name }}/" --flat
               fi
             fi
+
+            # On feature repositories, recalculate metadata when delivery is completed since this is not done manually on those
+            if [[ "${{ inputs.delivery_type }}" == "feature" ]]; then
+              curl -H "Authorization: Bearer ${{ env.JF_ACCESS_TOKEN }}" -X POST "${{ env.JF_URL }}/artifactory/api/yum/$ROOT_REPO_PATH?path=/${{ inputs.version }}/${{ inputs.distrib }}/${{ inputs.stability }}/$ARCH&async=0"
+            fi
           done
         done
 
         # In case of CMA, we also copy it in /installers
-        if [[ "${{ inputs.module_name }}" == "monitoring-agent" ]]; then
+        if [[ "${{ inputs.module_name }}" == "monitoring-agent" ]] && [[ "${{ inputs.delivery_type }}" == "classic" ]]; then
           for FILE in $FILES; do
             echo "[DEBUG] - File: $FILE"
 
