add DEB promote to nexus

diff --git a/.github/actions/promote-to-stable/action.yml b/.github/actions/promote-to-stable/action.yml
--- a/.github/actions/promote-to-stable/action.yml
+++ b/.github/actions/promote-to-stable/action.yml
@@ -160,4 +160,75 @@ runs:
           done
         done
 
+        # Update repository metadata
+        METADATAS=`echo "$METADATAS" | xargs -n1 | sort -u | xargs`
+        for METADATA in `echo $METADATAS`; do
+          ssh -o StrictHostKeyChecking=no "${{ inputs.yum_repo_address }}" "sh "${{ inputs.update_repo_path }}" $METADATA" 2>&-
+        done
+
+        # Invalidate cloudfront cache
+        ID="${{ inputs.cloudfront_id }}"
+        # Remove duplicated invalidation paths
+        INVALIDATION_PATHS=`echo "$INVALIDATION_PATHS" | xargs -n1 | sort -u | xargs`
+        ITERATIONS=1
+        for INVALIDATION_PATH in `echo $INVALIDATION_PATHS`; do
+          until aws cloudfront create-invalidation --distribution-id "$ID" --paths "$INVALIDATION_PATH"; do
+            if [ ${ITERATIONS} -eq 10 ]; then
+              return 0
+            fi
+            echo "couldn't invalidate cache, AWS quota might have been reached, retrying in 30 seconds..."
+            sleep 30s
+            ITERATIONS=$((ITERATIONS+1))
+          done
+        done
+
+      shell: bash
+
+    - name: Promote DEB package to stable on Nexus
+      if: ${{ startsWith(inputs.distrib, 'bullseye') }}
+      run: |
+        set -x
+        echo "[DEBUG] - Major version: ${{ inputs.major_version }}"
+        echo "[DEBUG] - Minor version: ${{ inputs.minor_version }}"
+        echo "[DEBUG] - Distrib: ${{ inputs.distrib }}"
+        echo "[DEBUG] - Repository name: ${{ inputs.repository_name }}"
+
+        # Handle only onprem repositories, build root repo path and target path
+        if [[ "${{ inputs.repository_name }}" == "standard" ]]; then
+          ROOT_REPO_PATH="${{ inputs.major_version }}-testing"
+          TARGET_PATH="https://apt.centreon.com/repository/${{ inputs.major_version }}"
+          echo "[DEBUG] - Target path: $TARGET_PATH"
+        else
+          echo "Invalid repository name: ${{ inputs.repository_name }}"
+          exit 1
+        fi
+
+        echo "[DEBUG] - Target path: $TARGET_PATH"
+        echo "[DEBUG] - Root repo path: $ROOT_REPO_PATH"
+
+        # Promote testing packages to stable.
+        # Create dir to receive artifacts to promote
+        mkdir -p artifacts_to_promote
+        cd artifacts_to_promote
+
+        # Check if artifacts to promote
+        echo "[DEBUG] - Get path of testing DEB packages to promote to stable."
+        SRC_PATHS=$(curl -s -u "${{ inputs.nexus_username }}":"${{ inputs.nexus_password }}" "https://apt.centreon.com/service/rest/v1/search/assets?repository=${ROOT_REPO_PATH}&name=*${{ inputs.module }}*&version=${{ inputs.major_version }}.${{ inputs.minor_version }}-1" |jq -r '.items[].downloadUrl')
+
+        # Checking if there are testing packages to promote and download them.
+        if [[ ${SRC_PATHS[@]} ]]; then
+          for SRC_PATH in ${SRC_PATHS[@]}; do
+            echo "[DEBUG] - Source path found: $SRC_PATH"
+            echo "[DEBUG] - Fetching artifact from $SRC_PATH."
+            curl -JOs $SRC_PATH
+            FILENAME=$(basename $SRC_PATH)
+            echo "[DEBUG] - Promoting testing artifact $FILENAME to stable."
+            #curl --fail -s -u "${{ inputs.nexus_username }}":"${{ inputs.nexus_password }}" -H "Content-Type: multipart/form-data" --data-binary "@./$FILENAME" $TARGET_PATH
+            rm -f $FILENAME
+            sleep 2
+          done
+        else
+          echo "[DEBUG] - No source path found."
+        fi
+
       shell: bash
