fix(ci): handle concurrent hotfix and release

diff --git a/.github/actions/promote-to-stable/action.yml b/.github/actions/promote-to-stable/action.yml
--- a/.github/actions/promote-to-stable/action.yml
+++ b/.github/actions/promote-to-stable/action.yml
@@ -25,6 +25,12 @@ inputs:
   github_base_ref:
     description: "Release base ref"
     required: true
+  release_type:
+    description: "Type of release (hotfix, release)"
+    required: true
+  release_cloud:
+    description: "Release context (cloud or not cloud)"
+    required: true
 
 runs:
   using: "composite"
@@ -37,10 +43,14 @@ runs:
     - name: Promote RPM packages to stable
       if: ${{ startsWith(inputs.distrib, 'el') }}
       run: |
-        set -x
+        set -eux
+
+        # DEBUG
         echo "[DEBUG] - Major version: ${{ inputs.major_version }}"
         echo "[DEBUG] - Minor version: ${{ inputs.minor_version }}"
         echo "[DEBUG] - Distrib: ${{ inputs.distrib }}"
+        echo "[DEBUG] - release_cloud: ${{ inputs.release_cloud }}"
+        echo "[DEBUG] - release_type: ${{ inputs.release_type }}"
 
         # Cloud specific promote
         # delivery by default to onprem, override to internal if base branch is master
@@ -50,9 +60,21 @@ runs:
           ROOT_REPO_PATH="rpm-standard"
         fi
 
+        # Build search path based on release_cloud and release_type values
+        # if cloud, search in testing-<release_type> path
+        # if non-cloud, search in the testing usual path
+        if [[ ${{ inputs.release_cloud }} -eq 1 && ${{ inputs.release_type }} == "hotfix" ]] || [[ ${{ inputs.release_cloud }} -eq 1 && ${{ inputs.release_type }} == "release" ]];then
+          SEARCH_REPO_PATH="${{ inputs.major_version }}/${{ inputs.distrib }}/testing-${{ inputs.release_type }}/$ARCH/${{ inputs.module_name }}"
+        elif [[ ${{ inputs.release_cloud }} -eq 0 ]];then
+          SEARCH_REPO_PATH="${{ inputs.major_version }}/${{ inputs.distrib }}/testing/$ARCH/${{ inputs.module_name }}"
+        else
+          echo "Invalid combination of release_type and release_cloud"
+        fi
+
+        # Search for testing packages candidate for promote
         for ARCH in "noarch" "x86_64"; do
           echo "[DEBUG] - Get artifactory path of $ARCH testing artifacts to promote to stable."
-          SRC_PATHS=$(jf rt s --include-dirs $ROOT_REPO_PATH/${{ inputs.major_version }}/${{ inputs.distrib }}/testing/$ARCH/${{ inputs.module_name }}/*.rpm | jq -r '.[].path')
+          SRC_PATHS=$(jf rt search --include-dirs $ROOT_REPO_PATH/$SEARCH_REPO_PATH/*.rpm | jq -r '.[].path')
           if [[ ${SRC_PATHS[@]} ]]; then
             for SRC_PATH in ${SRC_PATHS[@]}; do
               echo "[DEBUG] - Source path found: $SRC_PATH"
@@ -61,18 +83,26 @@ runs:
             echo "[DEBUG] - No source path found."
             continue
           fi
+
+          # Build target path based on ARCH
           echo "[DEBUG] - Build $ARCH artifactory target path."
           TARGET_PATH="$ROOT_REPO_PATH/${{ inputs.major_version }}/${{ inputs.distrib }}/${{ inputs.stability }}/$ARCH/RPMS/${{ inputs.module_name }}/"
           echo "[DEBUG] - Target path: $TARGET_PATH"
+
+          # Download candidates for promote
           echo "[DEBUG] - Promoting $ARCH testing artifacts to stable."
           for ARTIFACT in ${SRC_PATHS[@]}; do
             echo "[DEBUG] - Downloading $ARTIFACT from TESTING."
             jf rt download $ARTIFACT --flat
           done
+
+          # Upload previously downloaded candidates to TARGET_PATH
           for ARTIFACT_DL in $(dir|grep -E "*.rpm"); do
             echo "[DEBUG] - Promoting (upload) $ARTIFACT_DL to stable $TARGET_PATH."
             jf rt upload "$ARTIFACT_DL" "$TARGET_PATH" --flat
           done
+
+          # Cleanup before next round of candidates
           rm -f *.rpm
         done
       shell: bash
@@ -85,7 +115,7 @@ runs:
         echo "[DEBUG] - Distrib: ${{ inputs.distrib }}"
 
         echo "[DEBUG] - Get path of testing DEB packages to promote to stable."
-        SRC_PATHS=$(jf rt s --include-dirs apt-standard-${{ inputs.major_version }}-testing/pool/${{ inputs.module_name }}/*.deb | jq -r '.[].path')
+        SRC_PATHS=$(jf rt s --include-dirs apt-standard-${{ inputs.major_version }}-testing/pool/${{ inputs.module_name }}/${{ inputs.release_type }}/*.deb | jq -r '.[].path')
 
         if [[ ${SRC_PATHS[@]} ]]; then
           for SRC_PATH in ${SRC_PATHS[@]}; do
