fix

diff --git a/.github/actions/release/action.yml b/.github/actions/release/action.yml
--- a/.github/actions/release/action.yml
+++ b/.github/actions/release/action.yml
@@ -25,7 +25,7 @@ runs:
 
     - name: Get released versions for components
       run: |
-        set -eux
+        set -eu
         COMPONENTS_RELEASED=()
         COMPONENTS_OSS=("centreon-awie" "centreon-dsm" "centreon-gorgone" "centreon-ha" "centreon-open-tickets" "centreon-web")
         COMPONENTS_MODULES=("centreon-anomaly-detection" "centreon-autodiscovery" "centreon-bam" "centreon-cloud-business-extensions" "centreon-cloud-extensions" "centreon-it-edition-extensions" "centreon-license-manager" "centreon-map" "centreon-mbi" "centreon-pp-manager")
@@ -77,20 +77,20 @@ runs:
         echo "CURRENT_STABLE_BRANCH_MAJOR_VERSION=$CURRENT_STABLE_BRANCH_MAJOR_VERSION" >> "$GITHUB_ENV"
         echo "SCOPE_VERSION=$SCOPE_VERSION" >> "$GITHUB_ENV"
       shell: bash
+
     - name: Add new release tags to stable branch
       run: |
         # Add new stable tags to stable branch
-        echo "::notice::Configuring git."
-        # git config --global user.email "release@centreon.com"
-        # git config --global user.name "Centreon"
+        echo "Configuring git."
+        git config --global user.email "release@centreon.com"
+        git config --global user.name "Centreon"
 
         # Create release tags on git for each release components
-        echo "::notice::Creating release tags."
+        echo "Creating release tags."
         for TAG in ${NEW_STABLE_TAGS[@]}; do
           if [ -z $(git tag --list "$TAG" | head -n 1) ]; then
-            echo "Adding tag with name $TAG for $TAG."
-        #    git tag -a "$TAG" -m "$TAG"
-        #    git push --follow-tags
+            git tag -a "$TAG" -m "$TAG"
+            git push --follow-tags
             echo "::notice::Tagging branch with $TAG."
           else
             echo "::error::Release tag $TAG already exists, exiting."
@@ -102,7 +102,7 @@ runs:
     - name: Create GITHUB releases from new release tags
       run: |
         # Install gh cli
-        echo "::notice::Installing GH CLI."
+        echo "Installing GH CLI."
         if ! command -v gh &> /dev/null; then
           echo "Installing GH CLI."
           type -p curl >/dev/null || (sudo apt update && sudo apt install curl -y)
@@ -116,42 +116,48 @@ runs:
         fi
 
         # Create GITHUB release for each release components
-        echo "::notice::Creating GITHUB releases."
+        echo "Creating GITHUB releases."
         for TAG in ${NEW_STABLE_TAGS[@]}; do
-          echo "Creating release with title $TAG for tag $TAG."
-        #  gh release create $TAG --target "${{ inputs.github_ref_name }} --title "$TAG" --verify-tag
+          echo "::notice::Creating release with title $TAG for tag $TAG."
+          gh release create $TAG --target "${{ inputs.github_ref_name }} --title "$TAG" --verify-tag
         done
       shell: bash
 
     - name: Create stable JIRA versions from new release tags
       run: |
-        set -eux
+        set -eu
 
         # Call JIRA to provide new jira versions to create
         # Webhook url
         JIRA_INCOMING_WEBHOOK="${{ inputs.jira_webhook_url }}"
 
-        # Build JSON structure with released versions
-        RELEASE_JSON=$(jq -nc '{componentList: $ARGS.positional}' --args "${NEW_STABLE_TAGS[@]}")
+        # Rebuild NEW_STABLE_TAGS as an array
+        for i in ${NEW_STABLE_TAGS[@]}; do
+          NEW_RELEASE_TAGS+=("$i")
+        done
 
         # Create new JIRA versions (old way of doing it)
         # TODO: add a future capacity to determine wether the release is hotfix or standard (using TYPE)
         # OR: rely on jira automation to do it (less hassle on github side, and jira knows jira best)
 
-        # JIRA_VERSION_DATA="{\"archived\":false,\"releaseDate\":\"$(date +%Y-%m-%d)\",\"name\":\"centreon-${{ inputs.module_name }}-$NEW_VERSION\",\"description\":\"$TYPE:$RELEASE_ID\",\"projectId\":${{ inputs.jira_project_id }},\"released\":false}"
-        # echo "$JIRA_VERSION_DATA"
-        # curl --fail --request POST \
-        #   --url 'https://centreon.atlassian.net/rest/api/3/version' \
-        #   --header 'Authorization: Basic ${{ inputs.jira_token }}' \
-        #   --header 'Accept: application/json' \
-        #   --header 'Content-Type: application/json' \
-        #   --data ''$VERSION_DATA''
-
+        # Create JIRA version for each released component
+        echo "Creating JIRA releases."
+        for TAG in ${NEW_RELEASE_TAGS[@]}; do
+          echo "::notice::Creating JIRA release $TAG based on git release tag $TAG."
+          JIRA_VERSION_DATA="{\"archived\":false,\"releaseDate\":\"$(date +%Y-%m-%d)\",\"name\":\"$TAG\",\"projectId\":${{ inputs.jira_project_id }},\"released\":false}"
+          echo "Sending to JIRA release: $JIRA_VERSION_DATA"
+          # curl --fail --request POST \
+            --url 'https://centreon.atlassian.net/rest/api/3/version' \
+            --header 'Authorization: Basic ${{ inputs.jira_token }}' \
+            --header 'Accept: application/json' \
+            --header 'Content-Type: application/json' \
+            --data ''$VERSION_DATA''
+        done
       shell: bash
 
     - name: Trigger release communication for new releases
       run: |
-        set -eux
+        set -eu
         MAJOR_VERSION=$CURRENT_STABLE_BRANCH_MAJOR_VERSION
 
         # Webhook url
