feat(ci): allow parallel delivery of release and hotfix (#2956)

diff --git a/.github/actions/deb-delivery/action.yml b/.github/actions/deb-delivery/action.yml
--- a/.github/actions/deb-delivery/action.yml
+++ b/.github/actions/deb-delivery/action.yml
@@ -30,21 +30,24 @@ runs:
   using: "composite"
   steps:
     - name: Use cache DEB files
-      uses: actions/cache/restore@1bd1e32a3bdc45362d1e726936510720a7c30a57 # v4.2.0
+      uses: actions/cache/restore@5a3ec84eff668545956fd18022155c47e93e2684 # v4.2.3
       with:
         path: ./*.deb
         key: ${{ inputs.cache_key }}
         fail-on-cache-miss: true
 
-    - uses: jfrog/setup-jfrog-cli@0f30b43d62ccad81fba40748d2c671c4665b2d27 # v3.5.3
+    - uses: jfrog/setup-jfrog-cli@ff5cb544114ffc152db9cea1cd3d5978d5074946 # v4.5.11
       env:
         JF_URL: https://packages.centreon.com
         JF_ACCESS_TOKEN: ${{ inputs.artifactory_token }}
 
+    - name: Parse distrib name
+      id: parse-distrib
+      uses: ./.github/actions/parse-distrib
+      with:
+        distrib: ${{ inputs.distrib }}
+
     - name: Publish DEBs
-      env:
-        JF_URL: https://packages.centreon.com
-        JF_ACCESS_TOKEN: ${{ inputs.artifactory_token }}
       run: |
         FILES="*.deb"
 
@@ -58,18 +61,31 @@ runs:
 
         # Make sure all required inputs are NOT empty
         if [[ -z "${{ inputs.module_name }}" || -z "${{ inputs.distrib }}" || -z ${{ inputs.stability }} || -z ${{ inputs.version }} || -z "${{ inputs.is_cloud }}" ]]; then
-          echo "Some mandatory inputs are empty, please check the logs."
+          echo "::error::some mandatory inputs are empty, please check the logs."
           exit 1
         fi
 
-        # Set ROOT_REPO_PATH based on inputs
-        if [[ "${{ inputs.is_cloud }}" == "true" ]]; then
-            ROOT_REPO_PATH="apt-standard-internal-${{ inputs.stability }}"
-        elif [[ "${{ inputs.distrib }}" == "jammy" ]] || [[ "${{ inputs.distrib }}" == "noble" ]]; then
-          ROOT_REPO_PATH="ubuntu-standard-${{ inputs.version }}-${{ inputs.stability }}"
-        else
-          ROOT_REPO_PATH="apt-standard-${{ inputs.version }}-${{ inputs.stability }}"
+        if [[ "${{ inputs.stability }}" != "testing" && "${{ inputs.stability }}" != "unstable" ]]; then
+          echo "::error::stability must be one of: testing, unstable (got '${{ inputs.stability }}')"
+          exit 1
         fi
+
+        ROOT_REPO_PATH_PREFIX=""
+        if [[ "${{ steps.parse-distrib.outputs.distrib_family }}" == "debian" ]]; then
+          ROOT_REPO_PATH_PREFIX="apt-"
+        elif [[ "${{ steps.parse-distrib.outputs.distrib_family }}" == "ubuntu" ]]; then
+          ROOT_REPO_PATH_PREFIX="ubuntu-"
+        else
+          echo "::error::Unsupported distribution family: ${{ steps.parse-distrib.outputs.distrib_family }}"
+          exit 1
+        fi
+
+        ROOT_REPO_PATH_SUFFIX=""
+        if [[ "${{ inputs.is_cloud }}" == "true" ]]; then
+          ROOT_REPO_PATH_SUFFIX="-internal"
+        fi
+
+        ROOT_REPO_PATH="${ROOT_REPO_PATH_PREFIX}standard${ROOT_REPO_PATH_SUFFIX}"
 
         # Cleanup (equivalent to --sync-deletes done with RPMs)
         # This is a workaround the fact that jfrog cli does not allow upload
@@ -78,16 +94,15 @@ runs:
         # For each local artifact
         for file in $FILES; do
           # build a search pattern using ARTIFACT_BASENAME+OS_DISTRIB+ARCH
-          VERSION=${{ inputs.version }}
+          VERSION=${{ inputs.major_version }}
           BASENAME=$(echo "$file" | cut -d '_' -f 1)
           OS_DISTRIB=""
           ARCH=$(echo $file | cut -d '_' -f3 | cut -d '.' -f1)
 
-          # Handle debian or ubuntu distrib based on inputs.distrib
           if [[ "${{ inputs.distrib }}" == "jammy" ]] || [[ "${{ inputs.distrib }}" == "noble" ]]; then
             OS_DISTRIB=$(echo "$file" | sed -nE 's/.*(ubuntu\.[0-9]{2}\.[0-9]{2}).*/\1/p')
           elif [[ "${{ inputs.distrib }}" == "bullseye" ]] || [[ "${{ inputs.distrib }}" == "bookworm" ]]; then
-            OS_DISTRIB=$(echo "$file" | sed -nE 's/.*(deb[0-9]+).*/\1/p')
+            OS_DISTRIB=$(echo "$file" | sed -nE 's/.*(\+deb[0-9]+).*/\1/p')
           else
             echo "Distrib ${{ inputs.distrib }} is not supported as OS_DISTRIB."
           fi
@@ -98,7 +113,15 @@ runs:
           echo "[DEBUG] - OS_distrib: $OS_DISTRIB"
           echo "[DEBUG] - Arch: $ARCH"
 
-          SEARCH_PATH="$ROOT_REPO_PATH/pool/${{ inputs.module_name }}/${BASENAME}_*${OS_DISTRIB}*${ARCH}*.deb"
+          if [[ "${{ inputs.release_type }}" == "hotfix" || "${{ inputs.release_type }}" == "release" ]]; then
+            POOL_SUBPATH="${{ inputs.version }}/${{ inputs.stability }}/${{ inputs.release_type }}/${{ inputs.module_name }}"
+            DEB_PROP="${{ inputs.distrib }}-${{ inputs.version }}-${{ inputs.stability }}-${{ inputs.release_type }}/main/$ARCH"
+          else
+            POOL_SUBPATH="${{ inputs.version }}/${{ inputs.stability }}/${{ inputs.module_name }}"
+            DEB_PROP="${{ inputs.distrib }}-${{ inputs.version }}-${{ inputs.stability }}/main/$ARCH"
+          fi
+
+          SEARCH_PATH="$ROOT_REPO_PATH/pool/${POOL_SUBPATH}/${BASENAME}_*${OS_DISTRIB}*${ARCH}*.deb"
 
           # search and delete all remote artifacts matching this pattern
           echo "Searching and deleting $SEARCH_PATH"
@@ -106,8 +129,8 @@ runs:
 
           # upload local artifact
           echo "Uploading $file"
-          jf rt upload "$file" "$ROOT_REPO_PATH/pool/${{ inputs.module_name }}/" --deb "${{ inputs.distrib }}/main/$ARCH"
+          jf rt upload "$file" "$ROOT_REPO_PATH/pool/${POOL_SUBPATH}/" --flat --deb "${DEB_PROP}" --detailed-summary
         done
 
-        curl -H "Authorization: Bearer ${{ env.JF_ACCESS_TOKEN }}" -X POST "${{ env.JF_URL }}/artifactory/api/deb/reindex/$ROOT_REPO_PATH?async=1"
+        curl -H "Authorization: Bearer ${{ inputs.artifactory_token }}" -X POST "https://centreon.jfrog.io/artifactory/api/deb/reindex/$ROOT_REPO_PATH?async=0"
       shell: bash
