add outputs to get-version workflow

diff --git a/.github/workflows/get-version.yml b/.github/workflows/get-version.yml
--- a/.github/workflows/get-version.yml
+++ b/.github/workflows/get-version.yml
@@ -1,6 +1,16 @@
 on:
   workflow_call:
+    inputs:
+      version_file:
+        required: true
+        type: string
     outputs:
+      major_version:
+        description: "major version"
+        value: ${{ jobs.get-version.outputs.major_version }}
+      minor_version:
+        description: "minor version"
+        value: ${{ jobs.get-version.outputs.minor_version }}
       img_version:
         description: "docker image version (vcpkg checksum)"
         value: ${{ jobs.get-version.outputs.img_version }}
@@ -33,6 +43,8 @@ jobs:
   get-version:
     runs-on: ubuntu-22.04
     outputs:
+      major_version: ${{ steps.get_version.outputs.major_version }}
+      minor_version: ${{ steps.get_version.outputs.minor_version }}
       img_version: ${{ steps.get_version.outputs.img_version }}
       test_img_version: ${{ steps.get_version.outputs.test_img_version }}
       version: ${{ steps.get_version.outputs.version }}
@@ -64,10 +76,34 @@ jobs:
       - id: get_version
         run: |
           set -x
+
+          if [[ "${{ inputs.version_file }}" == */.version ]]; then
+            . .version
+            . ${{ inputs.version_file }}
+            VERSION="$MAJOR.$MINOR"
+          elif [[ "${{ inputs.version_file }}" == */CMakeLists.txt ]]; then
+            VERSION=$(awk '$1 ~ "COLLECT_MAJOR" {maj=substr($2, 1, length($2)-1)} $1 ~ "COLLECT_MINOR" {min=substr($2, 1, length($2)-1) ; print maj "." min}' CMakeLists.txt)
+            PATCH=$(awk '$1 ~ "COLLECT_PATCH" {print substr($2, 1, length($2) - 1)}' CMakeLists.txt)
+          else
+            echo "Unable to parse ${{ inputs.version_file }}"
+            exit 1
+          fi
+
+          echo "VERSION=$VERSION"
+
+          if egrep '^[2-9][0-9]\.[0-9][0-9]\.[0-9]+' <<<"$VERSION" >/dev/null 2>&1 ; then
+            n=${VERSION//[!0-9]/ }
+            a=(${n//\./ })
+            echo "major_version=${a[0]}.${a[1]}" >> $GITHUB_OUTPUT
+            MAJOR=${a[0]}.${a[1]}
+            echo "minor_version=${a[2]}" >> $GITHUB_OUTPUT
+          else
+            echo "Cannot parse version number from ${{ inputs.version_file }}"
+            exit 1
+          fi
+
           IMG_VERSION=$( cat `ls .github/docker/Dockerfile.centreon-collect-* | grep -v test` vcpkg.json | md5sum | awk '{print substr($1, 0, 8)}')
           TEST_IMG_VERSION=$(cat .github/docker/Dockerfile.centreon-collect-*-test .github/scripts/collect-prepare-test-robot.sh resources/*.sql | md5sum | cut -c1-8)
-          VERSION=$(awk '$1 ~ "COLLECT_MAJOR" {maj=substr($2, 1, length($2)-1)} $1 ~ "COLLECT_MINOR" {min=substr($2, 1, length($2)-1) ; print maj "." min}' CMakeLists.txt)
-          PATCH=$(awk '$1 ~ "COLLECT_PATCH" {print substr($2, 1, length($2) - 1)}' CMakeLists.txt)
           echo "img_version=$IMG_VERSION" >> $GITHUB_OUTPUT
           echo "test_img_version=$TEST_IMG_VERSION" >> $GITHUB_OUTPUT
           echo "version=$VERSION" >> $GITHUB_OUTPUT
