ci(gorgone): db should be ready before accessing it
Refs:MON-157180

diff --git a/.github/workflows/gorgone.yml b/.github/workflows/gorgone.yml
--- a/.github/workflows/gorgone.yml
+++ b/.github/workflows/gorgone.yml
@@ -143,6 +143,27 @@ jobs:
             centreon/www/install/createTables.sql
             centreon/www/install/createTablesCentstorage.sql
 
+      - name: wait mariadb initialization before creating databases
+        run: |
+          hostname=mariadb
+          max_attempts=20
+          attempt_num=1
+          echo "trying to access the database at $hostname"
+          set +e
+          while [ $attempt_num -le $max_attempts ]; do
+            output=$(mysql -h "$hostname" -u root -ppassword -e "SELECT 1;" 2>&1)
+            status=$?
+            if [ $status -eq 0 ]; then
+              echo "Attempt $attempt_num succeeded. Database is accessible."
+              exit 0
+            fi
+            echo "Attempt $attempt_num failed. Trying again in one second..."
+            sleep 1
+            attempt_num=$(( attempt_num + 1 ))
+          done
+          echo "failed accessing the database at $hostname after $max_attempts attempts : $output"
+          exit 1
+
       - name: Create databases
         run: |
           mysql -h mariadb -u root -ppassword -e "CREATE DATABASE \`centreon\`"
