fix(ci): replace job conditional by dedicated step (#1169)
* udpate release workflow

* udpate release action

* add feedbacks

* Update .github/workflows/release.yml

Co-authored-by: Kevin Duret <kduret@centreon.com>

* Remove unused arrays

---------

Co-authored-by: Kevin Duret <kduret@centreon.com>

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -20,9 +20,22 @@ on:
 
 jobs:
   release:
-    if: github.event.pull_request.merged == true && (github.base_ref == 'master' || github.base_ref == '[2-9][0-9].[0-9][0-9].x')
+    if: ${{ github.event.pull_request.merged == true }}
     runs-on: ubuntu-22.04
     steps:
+      - name: Check base_ref
+        run: |
+          set -eu
+          # Check if github.base_ref is either master or any of the supported version ones
+          # This must never run on any other than master and supported version base_ref
+          if [[ "${{ github.base_ref }}" == 'master' || "${{ github.base_ref }}" =~ ^[2-9][0-9].[0-9][0-9].x ]];then
+            echo "[DEBUG] base_ref is valid: ${{ github.base_ref }}"
+          else
+            echo "::error::base_ref is not valid (${{ github.base_ref }}), exiting."
+            exit 1
+          fi
+        shell: bash
+
       - name: Checkout sources
         uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
         with:
@@ -34,6 +47,6 @@ jobs:
         with:
           github_ref_name: ${{ github.head_ref || github.ref_name }}
           jira_project_id: ${{ secrets.JIRA_PROJECT_ID }}
-          jira_webhook_url: ${{ secrets.JIRA_RELEASE_WEBHOOK }}
           jira_user_email: ${{ secrets.XRAY_JIRA_USER_EMAIL }}
           jira_api_token: ${{ secrets.XRAY_JIRA_TOKEN }}
+          jira_webhook_url: ${{ secrets.JIRA_RELEASE_WEBHOOK }}
