to revert

diff --git a/.github/workflows/robot-test.yml b/.github/workflows/robot-test.yml
--- a/.github/workflows/robot-test.yml
+++ b/.github/workflows/robot-test.yml
@@ -55,227 +55,234 @@ on:
       jira_api_token:
         required: true
 jobs:
-  test-image-to-cache:
+  fail-build:
     runs-on: ${{ contains(inputs.image, 'arm') && 'centreon-collect-arm64' || 'ubuntu-24.04' }}
     steps:
-      - name: Checkout sources
-        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
-
-      - name: Login to Registry
-        uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567 # v3.3.0
-        with:
-          registry: ${{ vars.DOCKER_INTERNAL_REGISTRY_URL }}
-          username: ${{ secrets.registry_username }}
-          password: ${{ secrets.registry_password }}
-
-      - name: Login to Proxy Registry
-        uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567 # v3.3.0
-        with:
-          registry: ${{ vars.DOCKER_PROXY_REGISTRY_URL }}
-          username: ${{ secrets.registry_username }}
-          password: ${{ secrets.registry_password }}
-
-      - name: load image
-        run: |
-          docker pull ${{ vars.DOCKER_INTERNAL_REGISTRY_URL }}/${{inputs.image_test}}
+      - name: Fail build
+        run: exit 1
         shell: bash
 
-      - name: image to disk
-        run: |
-          docker save -o ./${{inputs.image}} ${{ vars.DOCKER_INTERNAL_REGISTRY_URL }}/${{inputs.image_test}}
-        shell: bash
+  # test-image-to-cache:
+  #   runs-on: ${{ contains(inputs.image, 'arm') && 'centreon-collect-arm64' || 'ubuntu-24.04' }}
+  #   steps:
+  #     - name: Checkout sources
+  #       uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
 
-      - name: image to cache
-        uses: actions/cache/save@d4323d4df104b026a6aa633fdb11d772146be0bf # v4.2.2
-        with:
-          path: ./${{inputs.image}}
-          key: ${{inputs.image_test}}
+  #     - name: Login to Registry
+  #       uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567 # v3.3.0
+  #       with:
+  #         registry: ${{ vars.DOCKER_INTERNAL_REGISTRY_URL }}
+  #         username: ${{ secrets.registry_username }}
+  #         password: ${{ secrets.registry_password }}
 
-  robot-test-list:
-    needs: [test-image-to-cache]
-    runs-on: ubuntu-24.04
-    outputs:
-      features: ${{ steps.list-features.outputs.features }}
+  #     - name: Login to Proxy Registry
+  #       uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567 # v3.3.0
+  #       with:
+  #         registry: ${{ vars.DOCKER_PROXY_REGISTRY_URL }}
+  #         username: ${{ secrets.registry_username }}
+  #         password: ${{ secrets.registry_password }}
 
-    steps:
-      - name: Checkout sources
-        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
+  #     - name: load image
+  #       run: |
+  #         docker pull ${{ vars.DOCKER_INTERNAL_REGISTRY_URL }}/${{inputs.image_test}}
+  #       shell: bash
 
-      - name: List features
-        id: list-features
-        run: |
-          cd tests
-          if [ "${{ inputs.only_robot_cma }}" == "true" ]
-          then
-            FEATURES_PATTERN="cma.robot"
-          else
-            FEATURES_PATTERN=".robot"
-          fi
-          echo "features=$(grep -Rl '*** Test Cases ***' . | grep "$FEATURES_PATTERN" | sed -e "s#^./##" | sort | jq -R -s -c 'split("\n")[:-1]')" >> $GITHUB_OUTPUT
+  #     - name: image to disk
+  #       run: |
+  #         docker save -o ./${{inputs.image}} ${{ vars.DOCKER_INTERNAL_REGISTRY_URL }}/${{inputs.image_test}}
+  #       shell: bash
 
-  robot-test:
-    needs: [robot-test-list]
-    runs-on: ${{ contains(inputs.image, 'arm') && 'centreon-collect-arm64' || 'ubuntu-24.04' }}
+  #     - name: image to cache
+  #       uses: actions/cache/save@d4323d4df104b026a6aa633fdb11d772146be0bf # v4.2.2
+  #       with:
+  #         path: ./${{inputs.image}}
+  #         key: ${{inputs.image_test}}
 
-    strategy:
-      fail-fast: false
-      matrix:
-        feature: ${{ fromJson(needs.robot-test-list.outputs.features) }}
+  # robot-test-list:
+  #   needs: [test-image-to-cache]
+  #   runs-on: ubuntu-24.04
+  #   outputs:
+  #     features: ${{ steps.list-features.outputs.features }}
 
-    name: ${{ matrix.feature }} ${{inputs.test_group_name}}
+  #   steps:
+  #     - name: Checkout sources
+  #       uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
 
-    steps:
-      - name: Checkout sources
-        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
-        with:
-          fetch-depth: 0
+  #     - name: List features
+  #       id: list-features
+  #       run: |
+  #         cd tests
+  #         if [ "${{ inputs.only_robot_cma }}" == "true" ]
+  #         then
+  #           FEATURES_PATTERN="cma.robot"
+  #         else
+  #           FEATURES_PATTERN=".robot"
+  #         fi
+  #         echo "features=$(grep -Rl '*** Test Cases ***' . | grep "$FEATURES_PATTERN" | sed -e "s#^./##" | sort | jq -R -s -c 'split("\n")[:-1]')" >> $GITHUB_OUTPUT
 
-      - name: Restore image
-        uses: actions/cache/restore@d4323d4df104b026a6aa633fdb11d772146be0bf # v4.2.2
-        with:
-          path: ./${{inputs.image}}
-          key: ${{inputs.image_test}}
-          fail-on-cache-miss: true
+  # robot-test:
+  #   needs: [robot-test-list]
+  #   runs-on: ${{ contains(inputs.image, 'arm') && 'centreon-collect-arm64' || 'ubuntu-24.04' }}
 
-      - name: Restore packages
-        uses: actions/cache/restore@d4323d4df104b026a6aa633fdb11d772146be0bf # v4.2.2
-        with:
-          path: ${{ inputs.package_cache_path }}
-          key: ${{ inputs.package_cache_key }}
-          fail-on-cache-miss: true
+  #   strategy:
+  #     fail-fast: false
+  #     matrix:
+  #       feature: ${{ fromJson(needs.robot-test-list.outputs.features) }}
 
-      - name: load image
-        run: |
-          docker load --input ./${{ inputs.image }}
+  #   name: ${{ matrix.feature }} ${{inputs.test_group_name}}
 
-      - name: Test ${{ matrix.feature }}
-        env:
-          AWS_ACCESS_KEY_ID: ${{ secrets.collect_s3_access_key }}
-          AWS_SECRET_ACCESS_KEY: ${{ secrets.collect_s3_secret_key }}
-        run: |
-          docker run --rm --privileged --ulimit core=-1 --security-opt seccomp=unconfined \
-            -v $(pwd):/test_collect  \
-            --env AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID \
-            --env AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY \
-            --env AWS_BUCKET=centreon-collect-robot-report \
-            --workdir /test_collect \
-            ${{ vars.DOCKER_INTERNAL_REGISTRY_URL }}/${{inputs.image_test}} \
-            ./.github/scripts/collect-test-robot.sh \
-            ${{ matrix.feature }} ${{inputs.database_type}} ${{inputs.tests_params}}
+  #   steps:
+  #     - name: Checkout sources
+  #       uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
+  #       with:
+  #         fetch-depth: 0
 
-      # - name: Generate Xray Token
-      #   id: generate-xray-token
-      #   run: |
-      #     token_response=$(curl -H "Content-Type: application/json" -X POST --data "{\"client_id\": \"${{ secrets.XRAY_CLIENT_ID }}\", \"client_secret\": \"${{ secrets.XRAY_CLIENT_SECRET }}\"}" "https://xray.cloud.getxray.app/api/v1/authenticate")
-      #     xray_token=$(echo "$token_response" | sed -n 's/.*"\(.*\)".*/\1/p')
-      #     echo "xray_token=$xray_token" >> $GITHUB_OUTPUT
-      #   shell: bash
+  #     - name: Restore image
+  #       uses: actions/cache/restore@d4323d4df104b026a6aa633fdb11d772146be0bf # v4.2.2
+  #       with:
+  #         path: ./${{inputs.image}}
+  #         key: ${{inputs.image_test}}
+  #         fail-on-cache-miss: true
 
-      # - name: Send report to xrays
-      #   run: |
-      #     curl -H "Content-Type: multipart/form-data" -X POST -F info=@tests/issueFields.json -F results=@tests/output.xml -F testInfo=@tests/testIssueFields.json -H "Authorization: Bearer ${{ steps.generate-xray-token.outputs.xray_token }}" https://xray.cloud.getxray.app/api/v2/import/execution/robot/multipart
+  #     - name: Restore packages
+  #       uses: actions/cache/restore@d4323d4df104b026a6aa633fdb11d772146be0bf # v4.2.2
+  #       with:
+  #         path: ${{ inputs.package_cache_path }}
+  #         key: ${{ inputs.package_cache_key }}
+  #         fail-on-cache-miss: true
 
-      - name: Move reports
-        if: ${{ failure() }}
-        run: |
-          mkdir reports
-          FILE_PREFIX=`echo "${{ matrix.feature }}" | sed -e "s#/#__#g"`-${{inputs.test_group_name}}
-          if [ -d tests/failed ] ; then
-            cp -rp tests/failed reports/$FILE_PREFIX-failed
-            cp tests/log.html reports/$FILE_PREFIX-log.html
-            cp tests/output.xml reports/$FILE_PREFIX-output.xml
-          fi
+  #     - name: load image
+  #       run: |
+  #         docker load --input ./${{ inputs.image }}
 
-      - name: Replace / with - in the feature path
-        id: feature-path
-        if: always()
-        run: |
-          feature_name="${{ matrix.feature }}"
-          feature_name_with_dash="${feature_name//\//-}"
-          echo "Modified Feature Name: $feature_name_with_dash"
-          echo "feature_name_with_dash=$feature_name_with_dash" >> $GITHUB_OUTPUT
+  #     - name: Test ${{ matrix.feature }}
+  #       env:
+  #         AWS_ACCESS_KEY_ID: ${{ secrets.collect_s3_access_key }}
+  #         AWS_SECRET_ACCESS_KEY: ${{ secrets.collect_s3_secret_key }}
+  #       run: |
+  #         docker run --rm --privileged --ulimit core=-1 --security-opt seccomp=unconfined \
+  #           -v $(pwd):/test_collect  \
+  #           --env AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID \
+  #           --env AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY \
+  #           --env AWS_BUCKET=centreon-collect-robot-report \
+  #           --workdir /test_collect \
+  #           ${{ vars.DOCKER_INTERNAL_REGISTRY_URL }}/${{inputs.image_test}} \
+  #           ./.github/scripts/collect-test-robot.sh \
+  #           ${{ matrix.feature }} ${{inputs.database_type}} ${{inputs.tests_params}}
 
-      - name: Upload Test Results
-        if: ${{ failure() }}
-        uses: actions/upload-artifact@4cec3d8aa04e39d1a68397de0c4cd6fb9dce8ec1 # v4.6.1
-        with:
-          name: reports-${{inputs.test_group_name}}-${{ steps.feature-path.outputs.feature_name_with_dash }}
-          path: reports
-          retention-days: 1
+  #     # - name: Generate Xray Token
+  #     #   id: generate-xray-token
+  #     #   run: |
+  #     #     token_response=$(curl -H "Content-Type: application/json" -X POST --data "{\"client_id\": \"${{ secrets.XRAY_CLIENT_ID }}\", \"client_secret\": \"${{ secrets.XRAY_CLIENT_SECRET }}\"}" "https://xray.cloud.getxray.app/api/v1/authenticate")
+  #     #     xray_token=$(echo "$token_response" | sed -n 's/.*"\(.*\)".*/\1/p')
+  #     #     echo "xray_token=$xray_token" >> $GITHUB_OUTPUT
+  #     #   shell: bash
 
-  robot-test-report:
-    needs: [robot-test]
-    if: ${{ failure() }}
-    runs-on: ubuntu-24.04
+  #     # - name: Send report to xrays
+  #     #   run: |
+  #     #     curl -H "Content-Type: multipart/form-data" -X POST -F info=@tests/issueFields.json -F results=@tests/output.xml -F testInfo=@tests/testIssueFields.json -H "Authorization: Bearer ${{ steps.generate-xray-token.outputs.xray_token }}" https://xray.cloud.getxray.app/api/v2/import/execution/robot/multipart
 
-    steps:
-      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
+  #     - name: Move reports
+  #       if: ${{ failure() }}
+  #       run: |
+  #         mkdir reports
+  #         FILE_PREFIX=`echo "${{ matrix.feature }}" | sed -e "s#/#__#g"`-${{inputs.test_group_name}}
+  #         if [ -d tests/failed ] ; then
+  #           cp -rp tests/failed reports/$FILE_PREFIX-failed
+  #           cp tests/log.html reports/$FILE_PREFIX-log.html
+  #           cp tests/output.xml reports/$FILE_PREFIX-output.xml
+  #         fi
 
-      - name: Download Artifacts
-        uses: actions/download-artifact@cc203385981b70ca67e1cc392babf9cc229d5806 # v4.1.9
-        with:
-          pattern: reports-${{inputs.test_group_name}}-*
-          path: reports
-          merge-multiple: true
+  #     - name: Replace / with - in the feature path
+  #       id: feature-path
+  #       if: always()
+  #       run: |
+  #         feature_name="${{ matrix.feature }}"
+  #         feature_name_with_dash="${feature_name//\//-}"
+  #         echo "Modified Feature Name: $feature_name_with_dash"
+  #         echo "feature_name_with_dash=$feature_name_with_dash" >> $GITHUB_OUTPUT
 
-      - name: Upload the regrouped artifact
-        uses: actions/upload-artifact@4cec3d8aa04e39d1a68397de0c4cd6fb9dce8ec1 # v4.6.1
-        with:
-          name: reports-${{inputs.test_group_name}}
-          path: reports/
-          retention-days: 1
+  #     - name: Upload Test Results
+  #       if: ${{ failure() }}
+  #       uses: actions/upload-artifact@4cec3d8aa04e39d1a68397de0c4cd6fb9dce8ec1 # v4.6.1
+  #       with:
+  #         name: reports-${{inputs.test_group_name}}-${{ steps.feature-path.outputs.feature_name_with_dash }}
+  #         path: reports
+  #         retention-days: 1
 
-      - name: Delete separated artifacts
-        run: |
-          artifact_pattern="reports-${{inputs.test_group_name}}-"
-          TOKEN=${{ secrets.GITHUB_TOKEN }}
-          artifact_exist=true
-          while [ "$artifact_exist" = true ] ;do
-            artifact_exist=false
-            artifacts_response=$(curl -L \
-                          -H "Accept: application/vnd.github+json" \
-                          -H "Authorization: Bearer $TOKEN" \
-                          -H "X-GitHub-Api-Version: 2022-11-28" \
-                          "https://api.github.com/repos/${{ github.repository }}/actions/artifacts?per_page=100")
-            artifacts=$(echo $artifacts_response | jq -c '.artifacts[]')
-            echo "Those are the artifacts : $artifacts"
-            while read row; do
-              artifact_name=$(echo "$row" | jq -r '.name')
-              if [[ "$artifact_name" =~ ^.*"$artifact_pattern".* ]]; then
-                artifact_exist=true
-                echo "Deleting : $artifact_name"
-                artifact_id=$(echo "$row" | jq -r '.id')
-                curl -L \
-                  -X DELETE \
-                  -H "Accept: application/vnd.github+json" \
-                  -H "Authorization: Bearer $TOKEN" \
-                  -H "X-GitHub-Api-Version: 2022-11-28" \
-                  "https://api.github.com/repos/${{ github.repository }}/actions/artifacts/${artifact_id}"
-              fi
-            done <<< "$artifacts"
-          done
-          echo "End of Deleting"
-        shell: bash
+  # robot-test-report:
+  #   needs: [robot-test]
+  #   if: ${{ failure() }}
+  #   runs-on: ubuntu-24.04
 
-      - uses: actions/setup-python@42375524e23c412d93fb67b49958b491fce71c38 # v5.4.0
-        with:
-          python-version: "3.10"
+  #   steps:
+  #     - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
 
-      - run: |
-          pip3 install -U robotframework robotframework-databaselibrary pymysql python-dateutil
-          cd reports
-          rebot -o output.xml ./*-output.xml || true
-        shell: bash
+  #     - name: Download Artifacts
+  #       uses: actions/download-artifact@cc203385981b70ca67e1cc392babf9cc229d5806 # v4.1.9
+  #       with:
+  #         pattern: reports-${{inputs.test_group_name}}-*
+  #         path: reports
+  #         merge-multiple: true
 
-      - name: Send report to commit
-        uses: joonvena/robotframework-reporter-action@229b6d4248b20be6e54f4fc32c7414130d1bf200 # v2.5
-        with:
-          gh_access_token: ${{ secrets.GITHUB_TOKEN }}
-          report_path: reports
-          show_passed_tests: false
+  #     - name: Upload the regrouped artifact
+  #       uses: actions/upload-artifact@4cec3d8aa04e39d1a68397de0c4cd6fb9dce8ec1 # v4.6.1
+  #       with:
+  #         name: reports-${{inputs.test_group_name}}
+  #         path: reports/
+  #         retention-days: 1
+
+  #     - name: Delete separated artifacts
+  #       run: |
+  #         artifact_pattern="reports-${{inputs.test_group_name}}-"
+  #         TOKEN=${{ secrets.GITHUB_TOKEN }}
+  #         artifact_exist=true
+  #         while [ "$artifact_exist" = true ] ;do
+  #           artifact_exist=false
+  #           artifacts_response=$(curl -L \
+  #                         -H "Accept: application/vnd.github+json" \
+  #                         -H "Authorization: Bearer $TOKEN" \
+  #                         -H "X-GitHub-Api-Version: 2022-11-28" \
+  #                         "https://api.github.com/repos/${{ github.repository }}/actions/artifacts?per_page=100")
+  #           artifacts=$(echo $artifacts_response | jq -c '.artifacts[]')
+  #           echo "Those are the artifacts : $artifacts"
+  #           while read row; do
+  #             artifact_name=$(echo "$row" | jq -r '.name')
+  #             if [[ "$artifact_name" =~ ^.*"$artifact_pattern".* ]]; then
+  #               artifact_exist=true
+  #               echo "Deleting : $artifact_name"
+  #               artifact_id=$(echo "$row" | jq -r '.id')
+  #               curl -L \
+  #                 -X DELETE \
+  #                 -H "Accept: application/vnd.github+json" \
+  #                 -H "Authorization: Bearer $TOKEN" \
+  #                 -H "X-GitHub-Api-Version: 2022-11-28" \
+  #                 "https://api.github.com/repos/${{ github.repository }}/actions/artifacts/${artifact_id}"
+  #             fi
+  #           done <<< "$artifacts"
+  #         done
+  #         echo "End of Deleting"
+  #       shell: bash
+
+  #     - uses: actions/setup-python@42375524e23c412d93fb67b49958b491fce71c38 # v5.4.0
+  #       with:
+  #         python-version: "3.10"
+
+  #     - run: |
+  #         pip3 install -U robotframework robotframework-databaselibrary pymysql python-dateutil
+  #         cd reports
+  #         rebot -o output.xml ./*-output.xml || true
+  #       shell: bash
+
+  #     - name: Send report to commit
+  #       uses: joonvena/robotframework-reporter-action@229b6d4248b20be6e54f4fc32c7414130d1bf200 # v2.5
+  #       with:
+  #         gh_access_token: ${{ secrets.GITHUB_TOKEN }}
+  #         report_path: reports
+  #         show_passed_tests: false
 
   create-jira-nightly-ticket:
-    needs: [robot-test-list, robot-test, robot-test-report]
+    needs: [fail-build]
     runs-on: ubuntu-24.04
     if: |
       inputs.is_nightly == 'true' && github.run_attempt == 1 &&
