fix 2

diff --git a/.github/workflows/veracode-analysis.yml b/.github/workflows/veracode-analysis.yml
--- a/.github/workflows/veracode-analysis.yml
+++ b/.github/workflows/veracode-analysis.yml
@@ -45,8 +45,13 @@ jobs:
     steps:
       - uses: actions/checkout@v4
 
-      - name: debug me
-        run: echo "tata"
+      - name: Double check github event
+        run: |
+          CHECK_BRANCH=`echo "${{ github.ref_name }}" | cut -d'/' -f2`
+          if [[ $CHECK_BRANCH == "merge" ]]; then
+            echo "[ERROR] - Event : ${{ github.event_name }} on PR branch should not have triggered this action"
+            exit 1
+          fi
 
       - name: Compiling Cpp sources
         run: |
@@ -148,7 +153,7 @@ jobs:
 
       - name: Promote latest scan
         # Only last develop should be promoted to policy scan
-        if: github.ref_name == 'disabled_develop' && github.events != "pull-request" # disable promote for now
+        if: github.ref_name == 'disabled_develop' # disable promote for now
         env:
           VERACODE_API_ID: "${{ secrets.veracode_api_id }}"
           VERACODE_API_SECRET: "${{ secrets.veracode_api_key }}"
